### ISSUE TITLE
connection close and HTTPS

### ISSUE THREAD

**Issue by adrianroe** [ninenines/gun#150] opened 2018-04-24 17:09 UTC
The combination of "connection close"  and HTTPS causes data loss or `{error,{closed,"The connection was lost."}}`

There is a very simple repro in [this gist](https://gist.github.com/adrianroe/63d62810b36fe5da306a50fe7f09ee81)

The gist pulls a file from a CDN that is available over HTTP and HTTPS, optionally setting the connection close header.  Of the 4 combinations, all work as expected other than the combination of HTTPS and connection close...  This almost always fails with the below, although it can also simply return less data that you would expect (i.e. a good response, but with the data truncated before the end)
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.3  (abort with ^G)
1> test_close:get(80, true).
140421
140421
140421
140421
140421
140421
140421
140421
140421
140421
ok
2> test_close:get(80, false).
140421
140421
140421
140421
140421
140421
140421
140421
140421
140421
ok
3> test_close:get(443, false).
140421
140421
140421
140421
140421
140421
140421
140421
140421
140421
ok
4> test_close:get(443, true).
** exception error: no match of right hand side value {error,{closed,"The connection was lost."}}
     in function  test_close:get_/4 (src/test_close.erl, line 23)
```

**Comment by adrianroe** [comment] 2018-04-24 17:13
I've tested the exact same connection with e.g. curl and all responses (including connection close with HTTPS) contain the full data... 

I'll take a look to see if it is anything obvious, but any thoughts warmly appreciated!

**Comment by essen** [comment] 2018-04-24 18:15
Can't reproduce. What Erlang version is this?

**Comment by adrianroe** [comment] 2018-04-24 18:52
The current repro is on Erlang 19 - I'll pull it to an Erlang 20 server as well.

The issue is definitely timing related - I can only reliably recreate it when I have a good internet connection (but not localhost!).  The current repro is on an AWS server.

**Comment by adrianroe** [comment] 2018-04-24 19:10
Just tried it locally (OSX - on both OTP 19 and 20) and don't see the issue.  I'm sure that it's because of the slowness of my internet connection!

I'll see if I can get a local only repro (gun -> cowboy) - or I can probably get you access to a cloud server where is can be repro'd

**Comment by essen** [comment] 2018-04-24 19:13
Run the commands I gave on the node with the issue (not via remote shell) and I'll be able to have a clearer idea of the issue.

**Comment by adrianroe** [comment] 2018-04-24 19:15
[trace.txt](https://github.com/ninenines/gun/files/1944230/trace.txt)

**Comment by adrianroe** [comment] 2018-04-24 19:28
[trace2.txt](https://github.com/ninenines/gun/files/1944268/trace2.txt)

**Comment by adrianroe** [comment] 2018-04-24 19:29
...and it does look like there is a related ssl issue
http://erlang.org/doc/apps/ssl/notes.html 

> 1.2  SSL 8.2.3
> Fixed Bugs and Malfunctions
> Packet options cannot be supported for unreliable transports, that is, packet option for DTLS over udp will not be supported.
> 
> Own Id: OTP-14664
> 
> Ensure data delivery before close if possible. This fix is related to fix in PR-1479.
> 
> Own Id: OTP-14794

**Comment by adrianroe** [comment] 2018-04-24 19:32
My repro box is running SSL 8.1.1 - I can't install 20 on that box, but might create a new server tomorrow with latest on it...

**Comment by essen** [comment] 2018-04-24 19:40
Yeah that's what I would guess happens. Relevant ticket is https://bugs.erlang.org/browse/ERL-420

And sorry about that, should have thought about it earlier, but a more interesting trace would be:

``` erlang
dbg:start().
dbg:tracer().
dbg:tpl(gun, []).
dbg:tpl(gun_http, []).
dbg:p(all, c).
```

**Comment by adrianroe** [comment] 2018-04-24 20:07
[trace3.txt](https://github.com/ninenines/gun/files/1944395/trace3.txt)
Thanks for the help!

**Comment by essen** [comment] 2018-04-24 20:14
Sounds like the Gun version is also old. What version is this?

**Comment by adrianroe** [comment] 2018-04-24 20:14
Head

**Comment by essen** [comment] 2018-04-24 20:27
There's a `gun_http:send_data_if_alive/1` call that doesn't exist, and then it immediately calls `gun:connect` without going through `retry_loop`? Really weird.

**Comment by essen** [comment] 2019-01-06 11:20
Since I've not been able to reproduce and it's been a while, and there's been a number of related ssl bugs fixed in recent Erlang/OTP versions, please try with the most recent version and reopen if there's still an issue. Thanks!

**Closed by essen** 2019-01-06 11:20 UTC

**Comment by adrianroe** [comment] 2019-01-12 10:07
For anyone watching this ticket - the symptoms of this ticket still persist - still caused by a (now different) issue in the Erlang SSL library.  See https://bugs.erlang.org/browse/ERL-371 for details.

We have experimented with the master branch referred to in ERL-371 which does indeed seem to prevent the issue.
