### ISSUE TITLE
HTTP/1 request with empty body and content-type header leaves connection in bad state

### ISSUE THREAD

**Issue by petrohi** [ninenines/gun#141] opened 2018-01-17 20:48 UTC
On subsequent request:

```
{:error,
 {:function_clause,
   [{:gun_http, :request,
     [{:http_state, #PID<0.200.0>,
       {:sslsocket, {:gen_tcp, #Port<0.6542>, :tls_connection, :undefined},
        #PID<0.247.0>}, :ranch_ssl, :"HTTP/1.1", [:gun_data], :keepalive, "",
       [], :head, {0, 0}, :body_chunked,
       #Function<0.21809937/1 in :gun_http.init/4>},
      #Reference<0.291734004.3684958210.98171>, #PID<0.200.0>, "PUT",
      'api.xyz.com', 443, "/some",
      [{"content-type", "application/json"}]],
     [file: '/Users/phizalev/machine_gun/deps/gun/src/gun_http.erl',
      line: 281]},
    {:gun, :loop, 1,
     [file: '/Users/phizalev/machine_gun/deps/gun/src/gun.erl', line: 683]},
    {:gun, :proc_lib_hack, 5,
     [file: '/Users/phizalev/machine_gun/deps/gun/src/gun.erl', line: 545]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
```

**Comment by essen** [comment] 2018-01-17 20:50
What do you mean by empty body? How do you call it?

**Comment by petrohi** [comment] 2018-01-17 20:52
Like this: `:gun.request(pid, "PUT", "/some", [{"content-type", "application/json"}], "", %{})`

**Comment by essen** [comment] 2018-01-17 21:00
That's not a bug per se, perhaps the interface is not obvious. If you set content-type but don't set a body you are expected to use the gun:data functions to send that body.

**Comment by petrohi** [comment] 2018-01-17 21:05
Would probably make sense for body be some atom in this case. But yes--makes sense.

**Comment by essen** [comment] 2018-01-17 21:26
Yes I don't disagree.

**Comment by essen** [comment] 2018-01-17 21:38
Let's keep it open if you don't mind, it'd be good to fix this, or at least error out earlier, at some point.

**Comment by essen** [comment] 2018-10-09 17:31
https://github.com/petrohi/machine_gun/issues/1 is an example real-world issue caused by this.

Also occurs for `gun:get/2`.

**Comment by petrohi** [comment] 2018-10-12 00:16
Should this be?

patch/4,5, post/4,5, put/4,5: *nofin*, body is provided as an argument

**Comment by essen** [comment] 2018-10-12 06:20
No by nofin I mean the data function can be called (the body isn't finished after the request call), while fin sends everything it gets and terminates the request.

**Comment by petrohi** [comment] 2018-10-12 15:54
Understand now. `request/4` with headers check is temporary for compatibility?

**Comment by essen** [comment] 2018-10-12 16:03
Yes until Gun 2.0. `request/4` would be removed then and you'd have to call one or the other function to be able to send body or not. So we'd still have the header issue for `patch/3`, `post/3`, `put/3` and `request/4` for now but `request/4` would be undocumented immediately in favor of the functions `headers/4,5`, and it's a lesser problem for the other 3.

**Comment by 9mm** [comment] 2018-12-17 04:01
So how do i need to deal with this? currently I have an API returning 80K req/min with "" body and no content-length

**Comment by 9mm** [comment] 2018-12-17 05:46
PS i should mention I'm using machine_gun

**Comment by essen** [comment] 2018-12-31 16:10
Please review 630bd47 which contains the proposed solution for Gun 2.0.

**Comment by essen** [comment] 2018-12-31 16:11
I'll close this meanwhile since I believe this is addressed but feel free to say otherwise or reopen. Thanks!

**Closed by essen** 2018-12-31 16:11 UTC
