### ISSUE TITLE
no function clause matching gun_http2:parse(<<>>,close)

### ISSUE THREAD

**Issue by leoliu** [ninenines/gun#105] opened 2016-10-01 03:19 UTC
Do `gun:open("fcm.googleapis.com", 443)` and wait a while to see SASL prints:

```
=CRASH REPORT==== 1-Oct-2016::11:15:02 ===
  crasher:
    initial call: gun:init/5
    pid: <0.3368.0>
    registered_name: []
    exception error: no function clause matching gun_http2:parse(<<>>,close) (/Users/leo/sources/erlang/test_gun/_build/default/lib/gun/src/gun_http2.erl, line 77) 
      in function  gun:loop/1 (/Users/leo/sources/erlang/test_gun/_build/default/lib/gun/src/gun.erl, line 584)
    ancestors: [gun_sup,<0.3142.0>]
    messages: []
    links: [<0.3143.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 4071
  neighbours:
```

**Comment by leoliu** [comment] 2016-10-01 08:51
This is due to `gun_http2:frame/2` called in `gun_http2:parse/2` may not return `##http2_state`.

**Comment by essen** [comment] 2016-10-03 20:16
Thanks! And sorry I did not see before, I am trying to solve a problem where I don't receive many emails from github.

**Comment by manifest** [comment] 2017-06-16 11:29
I've got the same issue after upgrading to latest vesion of Cowboy (2.0.0-pre.9).

**Comment by manifest** [comment] 2017-06-16 12:15
It hasn't reproduced locally, but always on Travis CI.
https://travis-ci.org/manifest/datastore/builds/243632587#L3204-L3213

**Comment by edgurgel** [comment] 2017-08-20 07:06
I get the same error after some time that the connection is up. 

```
{:DOWN, #Reference<0.0.2.22>, :process, #PID<0.204.0>,
  {:function_clause,
   [{:gun_http2, :parse, ["", :close], [file: 'src/gun_http2.erl', line: 106]},
    {:gun, :loop, 1, [file: 'src/gun.erl', line: 639]},
    {:gun, :proc_lib_hack, 5, [file: 'src/gun.erl', line: 528]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}]
```

I will try to send a PR later this week

**Comment by edgurgel** [comment] 2017-08-20 08:20
From what I can see this is the last frame sent before the error comes up:

```
{goaway,0,enhance_your_calm,<<"too_many_pings">>}
```

**Comment by essen** [comment] 2017-08-20 08:58
Ah makes sense. Also sounds like the default for pings might be too low if a server complains. Which server is it?

**Comment by edgurgel** [comment] 2017-08-20 09:01
This is GCM (Google Cloud Messaging) for push notifications:

"gcm-http.googleapis.com"

I'm playing with different keepalives now to see what's a good number.

**Comment by edgurgel** [comment] 2017-08-20 09:10
So should we change `frame` to not call `terminate` And leave it `parse` to call terminate with the reason? Thanks for the quick feedback :)

**Comment by essen** [comment] 2017-08-20 10:29
I think so.

**Comment by edgurgel** [comment] 2017-08-28 21:31
I'm unsure if we should distinguish between which type of `goaway` was sent but for now I'm just passing `close` back from `frame`

**Comment by essen** [comment] 2017-08-28 21:38
I think your PR changes are fine, I'm just wondering about testing. I'll get back to you.

**Comment by essen** [comment] 2017-09-02 12:58
Guess we can close this. Please open a new ticket (or PR) if you figure out a better timeout value. Thanks!

**Closed by essen** 2017-09-02 12:58 UTC
Labels: Bug
