### ISSUE TITLE
Unexpected event in state :connected of type :info: 

### ISSUE THREAD

**Issue by gaynetdinov** [ninenines/gun#193] opened 2019-02-26 12:14 UTC
Hello,

sometimes I see the following error from my app in the logs

```
{#Reference<0.884867089.3395289089.120418>, :badarg} {:state, #PID<0.32267.3>,

#Reference<0.884867089.3348627458.55187>, 'myhost.com', 80, 'myhost.com', 80, [], %{connect_timeout: 600000, http2_opts: %{keepalive: :infinity}, http_opts: %{keepalive: :infinity}, retry: 10, retry_timeout: 100}, :undefined, #Port<0.1623615>, :gun_tcp, {:tcp, :tcp_closed, :tcp_error}, :gun_http, {:http_state, #PID<0.32267.3>, #Port<0.1623615>, :gun_tcp, :"HTTP/1.1", [:gun_data_h], :keepalive, "", [], :head, {0, 0}, :head, #Function<0.25310258/1 in :gun_http.init/4>}}
```

I see where it happens in the codebase, but I have hard times to track it down in order to figure out why it happens and how to prevent it. Could you please give me some hints? 

Thank you!

**Comment by essen** [comment] 2019-02-26 18:42
This is what I wrote when I investigated it for a customer last month:

> About the {#Ref<0.1979334955.3890479110.82550>,badarg} message, I investigated as best as I could and my recommendation is to upgrade to a more recent OTP version as I can reproduce it with 20.1 but I can't reproduce it with 21.2.

So please try upgrading and if it still happens in 21.2 then I have no clue at this time.

**Comment by gaynetdinov** [comment] 2019-03-21 13:08
It still happens on 21.3.

**Comment by essen** [comment] 2019-03-21 13:10
I heard the same elsewhere earlier today. Something that could help would be a small snippet that reliably reproduces the problem for you.

**Comment by zinid** [comment] 2019-04-27 07:23
Just for the record, I receive them a lot in my software too, especially during high load. I typically add a workaround like [this one](https://github.com/processone/rtb/blob/master/src/mod_mqtt.erl#L369).
This is clearly an Erlang bug and seems like version upgrades don't help.
Ah, and I don't know how to reproduce this reliably: the message only appears during high load.

**Comment by essen** [comment] 2019-04-27 12:03
Ports can send `{Ref, badarg}` as a response when something is wrong in various cases. Just gotta figure out which one I guess.

**Comment by essen** [comment] 2019-04-27 13:17
Could either of you add a log in Gun to log when `{Closed, Socket}` or `{Error, Socket, Reason}` is received and log at least the `owner_ref` from the state, plus the error, I have a suspicion the issue could be that we are trying to close the port while it is closing and this may create this weird message. Just run it until the next `{Ref, badarg}` and see if you get a match.

**Comment by essen** [comment] 2019-05-07 09:01
From 21.3.8:

```
  OTP-15295    Application(s): stdlib

               A bug in gen_statem has been fixed where the internal
               timeout message could arrive as an info to the callback
               module during high load due to incorrect use of
               asynchronous timer cancel.
```

I wonder if this could help.

**Comment by pankajsoni19** [comment] 2019-08-06 09:21
I am getting the same logs on my system. I am using shotgun master repo which is at `gun 1.3.0`
erlang version is > `22.0.7`

```
2019-08-06 09:03:49 =ERROR REPORT====
Unexpected message: {#Ref<0.4027614940.3190030337.21497>,badarg}
```

**Comment by essen** [comment] 2019-09-21 14:22
A workaround is to enable the option `{exit_on_close, false}`. I am not sure whether it has any ill effects though. I will open an OTP ticket with my findings because the error seems to be either in the `port_control` BIF or the `inet` driver.

**Comment by essen** [comment] 2019-09-21 14:50
The OTP ticket is: https://bugs.erlang.org/browse/ERL-1049

**Comment by essen** [comment] 2019-09-23 14:35
There's already a PR at https://github.com/erlang/otp/pull/2397

Please try and provide feedback!

**Comment by zinid** [comment] 2019-09-23 14:44
Thanks a lot for paying attention so closely to this problem!
Sadly, I don't have enough time to check the PR because I'm at another project ATM.

**Comment by essen** [comment] 2019-09-24 17:56
Since this is covered both in the OTP bug tracker and in an OTP PR, I'll be closing this. Thanks!

**Closed by essen** 2019-09-24 17:56 UTC
